FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src ./src

# We’ll just run the worker loop (no HTTP) for now
CMD ["python", "-m", "src.audio_extractor_service.run_worker"]
