"""Centralized prompt templates for analysis_service LLM calls.

Keep templates stable and reuse across modules.
"""

UTTERANCES_PLACEHOLDER = "{{UTTERANCES_JSON}}"

SPEAKER_ROLE_MAPPING_PROMPT_TEMPLATE = (
    'RETURN ONLY JSON. NO MARKDOWN. NO PROSE. NO EXTRA KEYS.\n\n'
    'TASK\n'
    'Map diarized speaker labels to roles in a therapy session excerpt using ONLY the provided utterances (chronological).\n\n'
    'INPUT\n'
    'You will receive a JSON array of utterances. Each item contains:\n'
    '- speaker_label (string)\n'
    '- text (string)\n'
    '- optional index/time fields\n\n'
    'HARD CONSTRAINTS\n'
    '- The input contains EXACTLY 2 unique speaker_label values.\n'
    '- You MUST assign roles exactly once each: one label = "therapist" and the other = "patient". No duplicates, no unknowns.\n'
    '- The output speaker_roles object MUST contain EXACTLY the two speaker_label values that appear in the input (dynamic keys). No missing labels. No extra labels.\n'
    '- confidence values MUST be JSON numbers (not strings) within [0.0, 1.0].\n'
    '- overall_confidence MUST be a JSON number within [0.0, 1.0].\n'
    '- reason strings MUST be ≤120 characters, high-level behavioral cues only, non-sensitive, and MUST NOT quote the transcript verbatim.\n'
    '- If any constraint cannot be satisfied, still output JSON with best-effort mapping and set overall_confidence ≤ 0.40.\n\n'
    'DEFINITIONS\n'
    '- Therapist = the dominant clinical facilitator overall (guides, reflects, structures), even if the patient occasionally asks questions.\n'
    '- Patient = primarily discloses personal experiences/feelings and responds to facilitation.\n\n'
    'DETERMINISTIC DECISION RULE\n'
    'Across the full excerpt, decide which label is more therapist-like using multiple cues (not a single keyword):\n'
    'Therapist evidence (higher weight):\n'
    '- session structure: check-in, agenda, goals, next steps, summarizing progress, time/plan management\n'
    '- reflective listening: summaries, reframes, validation, gentle challenges\n'
    '- facilitation questions that guide exploration\n'
    '- coping strategies or psychoeducation\n'
    'Patient evidence:\n'
    '- personal disclosures: emotions, experiences, symptoms, relationships, day-to-day events\n'
    '- narrative responses to questions, uncertainty/vulnerability\n'
    '- requests for help/clarification, reporting progress\n\n'
    'If cues are mixed, choose the mapping with the strongest overall separation across the excerpt and reduce confidence.\n\n'
    'CONFIDENCE (deterministic guidance)\n'
    '- Base overall_confidence = 0.55.\n'
    '- Increase toward 0.95 as cues strongly separate by label across many turns (especially structure/summaries/next steps).\n'
    '- Decrease toward 0.30 if excerpt is short or both labels show similar facilitation/disclosure patterns.\n'
    '- Per-speaker confidence should be close to overall_confidence but may differ by up to 0.10.\n\n'
    'OUTPUT (STRICT JSON OBJECT ONLY)\n'
    'Keys must match exactly: speaker_roles, overall_confidence.\n'
    'speaker_roles must be an object with exactly two keys: the two speaker_label strings from the input.\n'
    'Each value must be an object with exactly: role, confidence, reason.\n\n'
    'Required schema:\n'
    '{\n'
    '  "speaker_roles": {\n'
    '    "<LABEL_1_FROM_INPUT>": {"role": "therapist"|"patient", "confidence": number, "reason": string},\n'
    '    "<LABEL_2_FROM_INPUT>": {"role": "therapist"|"patient", "confidence": number, "reason": string}\n'
    '  },\n'
    '  "overall_confidence": number\n'
    '}\n\n'
    'NOW PROCESS THIS INPUT:\n'
    '{{UTTERANCES_JSON}}\n\n\n'
    'Example input (labels are dynamic, not speaker_0/1):\n'
    '[\n'
    '  {"speaker_label":"A","text":"Before we dive in, what would you like to focus on today?"},\n'
    '  {"speaker_label":"B","text":"I’ve been anxious most days and it’s hard to unwind after work."},\n'
    '  {"speaker_label":"A","text":"When you notice the anxiety rising, what’s usually happening right beforehand?"},\n'
    '  {"speaker_label":"B","text":"Usually after interactions at work. I keep thinking about what I said."},\n'
    '  {"speaker_label":"A","text":"Let’s map one recent example and then try a brief grounding strategy and decide a next step."}\n'
    ']\n\n\n'
    'Example output (speaker_roles keys exactly match A and B; confidences are numbers):\n'
    '{\n'
    '  "speaker_roles": {\n'
    '    "A": {"role":"therapist","confidence":0.9,"reason":"Guides structure, asks exploratory questions, offers strategy/next steps"},\n'
    '    "B": {"role":"patient","confidence":0.9,"reason":"Primarily discloses feelings/experiences and responds with narrative detail"}\n'
    '  },\n'
    '  "overall_confidence": 0.9\n'
    '}\n'
)
